### ISSUE TITLE
Error with the script starting

### ISSUE THREAD

**Issue by JohnnyS** [EntityEvolution/ev-platechanger#1]
[    c-scripting-core] Creating script environments for ev-platechanger
[    c-scripting-core] Failed to load script @es_extended/imports.lua.
[script:ev-platechang] Error loading script server/plate.lua in resource ev-platechanger: @ev-platechanger/server/plate.lua:61: attempt to index a nil value (global 'ESX')
[script:ev-platechang] stack traceback:
[script:ev-platechang] 	@ev-platechanger/server/plate.lua:61: in main chunk
[    c-scripting-core] Failed to load script server/plate.lua.

Got this off of a fresh install?
Using ESX v1 Final

**Comment by BombayV** [comment]
This is not support by default for esx v1 final.

fxmanifest: Remove the `@es_extended/imports.lua`

server.lua:  At the top of the file.
```lua

ESX                    = nil
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
```

client.lua: At the 
```lua
ESX                           = nil
Citizen.CreateThread(function()
	while ESX == nil do
		TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
		Citizen.Wait(10)
	end
end)
```

**Comment by JohnnyS** [comment]
> This is not support by default for esx v1 final.
> 
> fxmanifest: Remove the `@es_extended/imports.lua`
> 
> server.lua: At the top of the file.
> 
> ```lua
> ESX                    = nil
> TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
> ```
> 
> client.lua: At the
> 
> ```lua
> ESX                           = nil
> Citizen.CreateThread(function()
> 	while ESX == nil do
> 		TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
> 		Citizen.Wait(10)
> 	end
> end)
> ```

Applied those changes so I can open up the license plate but it doesnt change it at all.

Ok nvm I wasnt pressing insert oops, but it changes it but wont let me insert in the garage like I dont own the car. I am using luke_vehiclegarage

**Comment by BombayV** [comment]
I'll install that garage

**Comment by BombayV** [comment]
I have tested it and it seems to work fine. I don't know what the problem could be. I was able to buy a vehicle, save it, change plate, and save it.

**Comment by JohnnyS** [comment]
Odd i was trying this as the old one we had js four license plate stopped working not sure why. Seems like i have a script conflicting with those functions

**Comment by BombayV** [comment]
Yeah. BTW, I did some testing with the garage and it always seemed to change my plate even without using the resource. So idk.

**Comment by JohnnyS** [comment]
@BombayV  Did it also allow you to insert the car back in the garage after changing the plate?

**Comment by BombayV** [comment]
Yes. It did let me.
