### ISSUE TITLE
After changing plates vehicle wont park in garage

### ISSUE THREAD

**Issue by vulthrax** [EntityEvolution/ev-platechanger#3]
Ok i have something strange going on, I did not modify anything only removing the esx part  for not having errors in the script and the sql. I added the licenseplate in the shared.lua.  When i click the licenseplate or use it. The licenseplate editor pops up and i can change the licenseplate, after choosing a custom plate i click accept and everything works fine  the car has another plate but from the moment i try to park the car with the modded plate  it says this car is not owned and if i go out of the car there is no way to go back in it. (No vehicle keys). At this moment when this happens i can /dv the vehicle and pick it up at the impound and i recieve the car with a custom plate on it, so this makes me think serverwise everything is stored right but for some odd reason when i try to park it at a garage it won't let me and gives me the message: vehicle not owned. 

Anybody got an idea where i can fix this issue?

**Version** Latest
Errors in console doing process described above: None
Screen record of the event: https://streamable.com/6q5h1n

**Comment by BombayV** [comment]
This occurs because qb-garage only accepts 8 chars. You can change it in config.
